#!/usr/bin/env python
#from source.lib.include import *
#from source.lib.parameters import *
from _generic_plugin import *

class Module(GenericModule):
	def __init__(self):
		self.authors = [
			Author(name='', email='', web=''),
		]
		
		self.name = ''
		self.short_description = ''
		self.references = [
			'',
		]
		
		self.date = '2016-01-25'
		self.license = 'GNU GPLv2'
		self.version = '1.0'
		self.tags = [
			'',
		]
		self.description = 'This module is designed to be used as a template for new modules. For help with this madness, check the "template_commented" module.'
		self.kb_access = [
			'',
		]
		
		self.dependencies = {
			'': '',
		}
		self.changelog = ''

		self.ResetParameters()

	def ResetParameters(self):
		self.parameters = {
			'': Parameter(value='', mandatory=True, description=''),
		}

	def Check(self):
		self.kb_init()
		log.info('This module does not support check.')
	
	def Run(self):
		self.kb_init()

		# # # # # # # #
		# Define your code here
		
		# # # # # # # #
		pass
	

lib.module_objects.append(Module())
